spring:
  datasource:
    url: jdbc:mysql://211.159.225.217:3306/PyDesign?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: Admin123.
  devtools:
    restart:
      enabled: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false