spring:
  datasource:
    url: jdbc:mysql://175.178.47.147:3306/PyDesign?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  devtools:
    restart:
      enabled: true
  cors:
    allowed-origins: "*"
    allowed-methods: GET,POST,PUT,DELETE
  jackson:
    time-zone: Asia/Shanghai

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
server:
  port: 8001